import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gmarketSans = localFont({
  src: "../assets/fonts/GmarketSansTTFMedium.ttf",
  display: "swap",
  variable: "--font-gmarket-sans",
});

export const metadata: Metadata = {
  title: "Code Path",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased ${gmarketSans.className}`}>{children}</body>
    </html>
  );
}
